application: wf-dominicfrost
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  login: optional

- url: /src/bundle.js
  static_files: src/bundle.js
  upload: src/bundle.js
  login: optional

# Public Tools

- url: /tools/jquery.js
  static_files: node_modules/jquery/dist/jquery.js
  upload: node_modules/jquery/dist/jquery.js

- url: /tools/react.js
  static_files: node_modules/react/react.js
  upload: node_modules/react/react.js

- url: /tools/bootstrap.js
  static_files: node_modules/bootstrap/dist/js/bootstrap.js
  upload: node_modules/bootstrap/dist/js/bootstrap.js

- url: /tools/bootstrap.css
  static_files: node_modules/bootstrap/dist/css/bootstrap.css
  upload: node_modules/bootstrap/dist/css/bootstrap.css

- url: /tools/bootstrap.css.map
  static_files: node_modules/bootstrap/dist/css/bootstrap.css.map
  upload: node_modules/bootstrap/dist/css/bootstrap.css.map

# Server Side

- url: /
  script: _go_app
  login: optional

- url: /loginHandler
  script: _go_app
  login: optional

- url: /.*
  script: _go_app
  login: optional

# Shared Dependencies

- url: /require.config.js
  static_files: require.config.js
  upload: require.config.js
  login: optional

